-- FRIEND GUP SHUP - SIMPLE DIRECT CHAT
-- No friend requests
-- No accept / decline
-- Search username -> Chat immediately

-- 1. Create tables if they do not exist

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    friend_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    username TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    friend_id BIGINT NOT NULL
        REFERENCES public.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id TEXT NOT NULL,
    receiver_id TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 2. Add username if it is missing

ALTER TABLE public.users
ADD COLUMN IF NOT EXISTS username TEXT;


-- 3. Turn OFF RLS for this simple app

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.friendships DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;


-- 4. Remove old policies

DROP POLICY IF EXISTS users_select ON public.users;
DROP POLICY IF EXISTS users_insert ON public.users;
DROP POLICY IF EXISTS users_update ON public.users;
DROP POLICY IF EXISTS users_delete ON public.users;

DROP POLICY IF EXISTS friendships_select ON public.friendships;
DROP POLICY IF EXISTS friendships_insert ON public.friendships;
DROP POLICY IF EXISTS friendships_update ON public.friendships;
DROP POLICY IF EXISTS friendships_delete ON public.friendships;

DROP POLICY IF EXISTS messages_select ON public.messages;
DROP POLICY IF EXISTS messages_insert ON public.messages;
DROP POLICY IF EXISTS messages_update ON public.messages;
DROP POLICY IF EXISTS messages_delete ON public.messages;


-- 5. Username indexes

DROP INDEX IF EXISTS public.users_username_unique;

CREATE UNIQUE INDEX users_username_unique
ON public.users (LOWER(username))
WHERE username IS NOT NULL;


CREATE INDEX IF NOT EXISTS users_username_search_idx
ON public.users (LOWER(username));


-- 6. Friendship indexes

CREATE INDEX IF NOT EXISTS friendships_user_idx
ON public.friendships (user_id);

CREATE INDEX IF NOT EXISTS friendships_friend_idx
ON public.friendships (friend_id);


-- 7. Message index

CREATE INDEX IF NOT EXISTS messages_chat_idx
ON public.messages (
    sender_id,
    receiver_id,
    created_at
);


-- 8. Permissions

GRANT USAGE ON SCHEMA public TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.users
TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.friendships
TO anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE
ON public.messages
TO anon, authenticated;


-- 9. Sequence permissions

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO anon, authenticated;


-- 10. Check RLS

SELECT
    schemaname,
    tablename,
    rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
AND tablename IN (
    'users',
    'friendships',
    'messages'
)
ORDER BY tablename;
