-- Friend Gup Shup - SIMPLE DIRECT CONNECT
--
-- This app has NO friend requests.
-- A user searches another user's username and taps Connect.
-- Both users are immediately linked and can chat.
--
-- Run this once in Supabase SQL Editor.
-- This keeps the existing users/friendships/messages design.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  friend_id text unique not null,
  name text not null,
  username text,
  created_at timestamptz default now()
);

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  friend_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, friend_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id text not null,
  receiver_id text not null,
  message text not null,
  created_at timestamptz default now()
);

-- Add username to old installations.
alter table public.users add column if not exists username text;

-- Give old users a username if they do not have one.
update public.users
set username = lower(
  regexp_replace(left(coalesce(name, 'friend'), 16), '[^a-zA-Z0-9_]', '', 'g')
) || id::text
where username is null or trim(username) = '';

-- Make usernames unique.
drop index if exists public.users_username_unique;
create unique index if not exists users_username_unique
on public.users (lower(username));

create index if not exists users_username_search_idx
on public.users (username);

create index if not exists friendships_user_idx
on public.friendships (user_id);

create index if not exists friendships_friend_idx
on public.friendships (friend_id);

create index if not exists messages_chat_idx
on public.messages (sender_id, receiver_id, created_at);

-- IMPORTANT FOR THIS SIMPLE APP:
-- The app does not use Supabase Auth. It uses a generated browser/profile ID.
-- Therefore RLS would block the simple client unless you add a full auth system.
-- Disable RLS for this demo/simple version so Connect and Chat work immediately.
-- Do not use this configuration for sensitive/private data.
alter table public.users disable row level security;
alter table public.friendships disable row level security;
alter table public.messages disable row level security;

-- Remove old policies if they exist. This also prevents duplicate-policy errors.
drop policy if exists users_select on public.users;
drop policy if exists users_insert on public.users;
drop policy if exists users_update on public.users;
drop policy if exists friendships_select on public.friendships;
drop policy if exists friendships_insert on public.friendships;
drop policy if exists friendships_update on public.friendships;
drop policy if exists messages_select on public.messages;
drop policy if exists messages_insert on public.messages;

-- Optional Realtime support for messages.
alter publication supabase_realtime add table public.messages;
