-- Friend Gup Shup - Supabase Database Schema
-- Run ALL of this in Supabase → SQL Editor → New query

create table if not exists users (
    id uuid primary key,
    display_name text not null
        check (char_length(display_name) between 1 and 40),
    friend_code text unique not null
        check (friend_code ~ '^[A-Z0-9]{8}$'),
    created_at timestamptz not null default now()
);

create table if not exists friendships (
    user_id uuid not null
        references users(id) on delete cascade,
    friend_id uuid not null
        references users(id) on delete cascade,
    friend_name text not null,
    created_at timestamptz not null default now(),

    primary key (user_id, friend_id)
);

create table if not exists messages (
    id bigint generated by default as identity primary key,

    sender_id uuid not null
        references users(id) on delete cascade,

    receiver_id uuid not null
        references users(id) on delete cascade,

    message text not null
        check (char_length(message) between 1 and 2000),

    created_at timestamptz not null default now()
);

-- Indexes for faster chat loading
create index if not exists messages_chat_idx
on messages(sender_id, receiver_id, created_at);

create index if not exists messages_receiver_idx
on messages(receiver_id, created_at);

create index if not exists messages_sender_idx
on messages(sender_id, created_at);

create index if not exists users_friend_code_idx
on users(friend_code);

-- Enable Row Level Security
alter table users enable row level security;
alter table friendships enable row level security;
alter table messages enable row level security;
